### ISSUE TITLE
Ready for grading Week13 Assignment

### ISSUE THREAD

**Issue by yqin-matc** [madisoncollege-it-programs/python-scripting-yqin-matc#16]
Hi Chris,

These are my week 13 assignments for interacting with web. I didn't upload the copied html file, just in case it won't run on your end.
Thank you for your support.
Best Regards,
Yan

**Comment by cethenmc** [comment]
Really nice job again.  8 out of 8.  One things to help you:  

In inspect-web.py, we should change the question to print both the link label and the link. Feel free to modify your print statement in your loop if you desire: print(f"{link.text}: {link.get('href')}")

No points off for that because it wasn't clear, but you can update your script on your end if you'd like.
