### ISSUE TITLE
Ready For Grading Week 5 Assignment File Data Interaction

### ISSUE THREAD

**Issue by yqin-matc** [madisoncollege-it-programs/python-scripting-yqin-matc#5]
Hi Chris,

This is my upload for week 5 assignment for the file data interaction.

Thank you very much.
Best,
Yan

**Comment by cethenmc** [comment]
Hi, Yan.  You have not satisfied the requirement for #3 with what you chose.  Specifically speaking, this clause:  "save the full file contents one line at a time to a variable."  I will record a 6 out of 8 until this is fixed.  Thanks!  Chris

**Comment by cethenmc** [comment]
Hello, Yan. Thanks for meeting with me last week. Thanks for walking through the way we intended for https://github.com/madisoncollege-it-programs/python-scripting-yqin-matc/issues/3 to be coded, and resubmitted. Since we spoke through some of the answers with when you would use the different read functions, I will not make you expand on those. Full credit now in grade book. But PLEASE don't forget that you can correct week3 yet as well.
