### ISSUE TITLE
Ready for grading week 7 assignment

### ISSUE THREAD

**Issue by yqin-matc** [madisoncollege-it-programs/python-scripting-yqin-matc#8]
Hi Chris,

This is my week 7 assignment for dictionaries.

Thank you.
Yan

**Comment by cethenmc** [comment]
Since the last three assignments have been this way, you will want to ensure whatever you do for these that you also do for the Midterm Activities.  The code behind this assignment is fairly intensive given the small ask.  Pretty impressive that you turned it out this way instead of the simpler way.  Most first time Python programmers would not have been able to do this.  

A few things worth mentioning.
# 5 was not intending for you to recreate the whole dictionary.  The request was intentionally placed after 2, 3 and 4 because we want to see you add a couple new items to an already created library.
# 6 and 7 were the nested loops that set you apart.  Others created their dictionaries to be more complex like yours, but this is where they got stuck.  The thing I really like is that you did this for all records, and if you had duplicates you counted those, too.  The this that surprises me, is for all of this complex effort, you still hard-coded 'server2.testlab.com' and 'server10.testlab.com' in your print statements, when you could have used test_value that you created earlier.

Still quite impressive work and you should be proud of it!!!!!

**I will record a 6 of 8 in the grade book for now, and I know we will go through this together when we meet.  After we meet you can resubmit for full credit.**

**Comment by yqin-matc** [comment]
Hi Chris, 
I've updated assignment's permission in week 7 through dos2unix. 
Please let me know if it's working or not.

Thank you.
Yan

**Comment by cethenmc** [comment]
It runs now, and it satisfies all of the requirements now that you simplified the dictionary.  I switched the score to 8 out of 8.

However, I am still confused regarding why you may not have chosen to simplify your answers once you simplified your dictionary.

You may want to copy your file (for your own study) and do the following:

#2 records.keys()
#3 records.values()
#4 records.items()

#6 and #7 just using an if "server10.netlab.com" in records:
